Fix convert-panel script so it can switch partition

diff --git a/recipes-vivint/vivutils/files/convert-panel b/recipes-vivint/vivutils/files/convert-panel
--- a/recipes-vivint/vivutils/files/convert-panel
+++ b/recipes-vivint/vivutils/files/convert-panel
@@ -1,9 +1,9 @@
 #!/bin/bash
-set -x
+#set -x
 
 QUIET=no
 SCRIPTNAME=$(basename "${BASH_SOURCE[0]}")
-set -e
+#set -e
 
 echo "$SCRIPTNAME"
 
@@ -62,9 +62,53 @@ ubootbinary() {
 	carp "unsupported platform looking for u-boot binary"
 }
 
+setbootnum() {
+	echo "Setting bootnum to $1"
+	fw_setenv bootnum $1
+}
+
+retry=0 
+verifybootnum(){
+        echo ***** Verify new bootnum  ****
+        new=$(fw_printenv bootnum)
+        echo "**** NEW bootnum $new ****"
+        if [ "$new"x != "bootnum=$1"x ]; then
+                let retry=$(expr $retry + 1)
+                echo "RETRY setting bootnum count $retry"
+                if [ $retry -gt 10 ]; then
+                        echo "###############################################################################"
+                        echo "### !!! FAILED to set bootnum, please re-run the convert script again. !!!! ###"
+                        echo "##############################################################################"
+                        emmcro 1
+                        exit 1
+		else
+                        setbootnum $1
+                        verifybootnum $1
+                fi
+        else
+                echo "Bootnum set!!!"
+        fi
+}
+
 #
 ubootupdate() {
 	confirmconversion
+
+	# find current boot num so we can set it after
+	cur_bootnum=$(fw_printenv bootnum | cut -d= -f2)
+        if [ -z $cur_bootnum ]; then
+		if grep -q mmcblk0p5 /proc/cmdline ; then
+			cur_bootnum=1
+		else
+			cur_bootnum=2
+		fi
+	fi
+
+        if [ $cur_bootnum -eq 1 ]; then
+                new_bootnum=2
+        else
+                new_bootnum=1
+        fi
 
 	emmcrw 0
 	dd if=/dev/zero of=/dev/mmcblk0boot0 bs=1024 count=2048
@@ -73,9 +117,14 @@ ubootupdate() {
 	sync
 	emmcro 0
 
-	# clearing u-boot env loses bootnum so leave it alone
+	# clearing u-boot env loses bootnum so re-set it after
 	emmcrw 1
 	dd if=/dev/zero of=/dev/mmcblk0boot1 bs=1024 count=2048
+
+	setbootnum $new_bootnum	
+
+	verifybootnum $new_bootnum
+
 	emmcro 1
 	
 	info "board re-setup complete, reboot..."
