Enforce requirement for initial conversion.  the Hub Plus image need to be on mmcblk0p5 for conversion need to be successful.

diff --git a/recipes-vivint/vivutils/files/convert-panel b/recipes-vivint/vivutils/files/convert-panel
--- a/recipes-vivint/vivutils/files/convert-panel
+++ b/recipes-vivint/vivutils/files/convert-panel
@@ -92,16 +92,21 @@ verifybootnum(){
 
 #
 ubootupdate() {
-	confirmconversion
 
-	# find current boot num so we can set it after
-	cur_bootnum=$(fw_printenv bootnum | cut -d= -f2)
-        if [ -z $cur_bootnum ]; then
-		if grep -q mmcblk0p5 /proc/cmdline ; then
-			cur_bootnum=1
+	if is_wallsly ; then
+		if  grep -q mmcblk0p5 /proc/cmdline ; then
+			confirmconversion
 		else
-			cur_bootnum=2
+			echo
+			echo "###############################################################"
+			echo "# FAILED TO CONVERT PANEL - PLEASE RUN THE QUICK UPDATE AGAIN #"
+			echo "# THEN RE-RUN THIS CONVERT SCRIPT - THANKS                    #"
+			echo "###############################################################"
+			echo
+			exit 1
 		fi
+	else
+		confirmconversion
 	fi
 
 	emmcrw 0
@@ -114,15 +119,10 @@ ubootupdate() {
 	# clearing u-boot env loses bootnum so re-set it after
 	emmcrw 1
 	dd if=/dev/zero of=/dev/mmcblk0boot1 bs=1024 count=2048
-
-	setbootnum $cur_bootnum	
-
-	verifybootnum $cur_bootnum
-
 	emmcro 1
 	
 	info "board re-setup complete, reboot..."
-	reboot -f
+	#reboot -f
 
 	exit 0
 }
