Fixed parsing of image file name so that it works with xz, gz, bz2.

diff --git a/recipes-vivint/vivutils/files/quick-update b/recipes-vivint/vivutils/files/quick-update
--- a/recipes-vivint/vivutils/files/quick-update
+++ b/recipes-vivint/vivutils/files/quick-update
@@ -29,6 +29,10 @@ version_file="version"
 logfile="/media/extra/update/.update_status"
 #logfile="/media/extra/update/.update_status_test" # TODO TEST logfile
 
+# To debug, uncomment the next 2 lines:
+#export PS4='+(${BASH_SOURCE}:${LINENO}):'
+#set -x
+
 main() {
 	
 	[ ! -f $logfile ] && touch $logfile && writelogonly "Created log file $logfile"
@@ -900,17 +904,19 @@ set_inactive_version() {
 }
 
 get_version_from_image_name() {
-
 	# Get the update version from the given image name
 	#   - to avoid dependency on manifest
 	# parameter 1: image name
 	# return the version
-    
-	v=""
-	[ $device == "wallsly" ] && v=$(cut -c31- <<< $1) && v=$(rev <<< $v) && v=$(cut -c16- <<< $v) && v=$(rev <<< $v)
-	[ $device == "slimline" ] && v=$(cut -c36- <<< $1) && v=$(rev <<< $v) && v=$(cut -c16- <<< $v) && v=$(rev <<< $v)
-	[ $device == "touchlink" ] && v=$(cut -c31- <<< $1) && v=$(rev <<< $v) && v=$(cut -c26- <<< $v) && v=$(rev <<< $v)
-	echo $v
+
+	v="$1"
+	rootfsmatcher="rootfs[.]tar[.](xz|bz2|gz)$"
+	if [[ $v =~ $rootfsmatcher ]]; then
+		v=$(echo "$v" | sed -E -e 's/^.*-//' -e 's/.rootfs.tar.*$//')
+		echo "$v"
+	else
+		echo "undefined"
+	fi
 }
 
 get_update_image_name() {
@@ -1098,7 +1104,9 @@ check_image_name_wallsly() {
 	if [[ $1 == $wallsly_image ]]; then
 		[ $debug -eq 0 ] || writelog "GOOD image name for a $product - $1"
 	else
-		usage "BAD image name \"$1\" for $product,$errors"; fi
+		echo "Invalid image name \"$1\" for $product,$errors"
+		exit 1
+	fi
 }
 
 check_image_name_slimline() {
@@ -1110,7 +1118,9 @@ check_image_name_slimline() {
 	if [[ $1 == $slimline_image ]]; then
 		[ $debug -eq 0 ] || writelog "GOOD image name for a $product - $1"
 	else
-		usage "BAD image name \"$1\" for $product,$errors"; fi
+		echo "Invalid image name \"$1\" for $product,$errors"
+		exit 1
+	fi
 }
 
 check_image_name_touchlink() {
@@ -1122,7 +1132,9 @@ check_image_name_touchlink() {
 	if [[ $1 == $touchlink_image ]]; then
 		[ $debug -eq 0 ] || writelog "GOOD image name for a $product - $1"
 	else
-		usage "BAD image name \"$1\" for $product,$errors"; fi
+		echo "Invalid image name \"$1\" for $product,$errors"
+		exit 1
+	fi
 }
 
 version() {
