SC-8794: remove unused variable; whitespace

diff --git a/recipes-vivint/vivutils/files/slimline-update b/recipes-vivint/vivutils/files/slimline-update
--- a/recipes-vivint/vivutils/files/slimline-update
+++ b/recipes-vivint/vivutils/files/slimline-update
@@ -4,8 +4,8 @@ image=$1
 
 if [[ `uname -a |cut -d' ' -f2` != "imx6dl-slimline" ]]
 then
-    echo "This is not Glance, quickie update refused!"
-    exit 6
+	echo "This is not Glance, quickie update refused!"
+	exit 6
 fi
 
 if [[ $image == "help" ]]
@@ -16,10 +16,10 @@ fi
 
 if [[ -z $image ]]
 then
-    echo "No image was specified. Please get an image from the update server and copy it to your panel."
-    echo "    http://updateseng.vivint.com/innovation/packages/branches/<version>/<build>/slimline-qt5-image-imx6dl-slimline-<version>.<build>.rootfs.tar.bz2 "
-    echo "Usage: $0 help|path_to_image_file"
-    exit 2
+	echo "No image was specified. Please get an image from the update server and copy it to your panel."
+	echo "    http://updateseng.vivint.com/innovation/packages/branches/<version>/<build>/slimline-qt5-image-imx6dl-slimline-<version>.<build>.rootfs.tar.bz2 "
+	echo "Usage: $0 help|path_to_image_file"
+	exit 2
 else
 	imagepath=`readlink -f $image`
 fi
@@ -49,7 +49,7 @@ echo "Installing..."
 # install and switch to new installation
 c_partition=$(cat /proc/cmdline | cut -d= -f3 | cut -d' ' -f1)
 
-if [[ $c_partition == '/dev/mmcblk0p6' ]] 
+if [[ $c_partition == '/dev/mmcblk0p6' ]]
 then
 	n_partition=/media/mmcblk0p5
 	dev_partition=/dev/mmcblk0p5
@@ -76,9 +76,9 @@ tar -C $n_partition -xvjf $image
 
 if [[ $? -ne 0 ]]
 then
-    echo "FAILED to extract files..."
-    echo "ABORT update..."
-    exit 5
+	echo "FAILED to extract files..."
+	echo "ABORT update..."
+	exit 5
 fi
 
 # moving network conf file
@@ -110,10 +110,10 @@ bootnum=$(fw_printenv bootnum | cut -d= -f2)
 echo 0 > /sys/block/mmcblk0boot1/force_ro
 
 if [[ $bootnum -eq 1 ]]
-then 
+then
 	fw_setenv bootnum 2
 elif [[ $bootnum -eq 2 ]]
-then 
+then
 	fw_setenv bootnum 1
 else
 	echo "Uh Oh, blindly setting bootnum to 2."
@@ -126,3 +126,4 @@ echo "Done, Rebooting..."
 reboot
 
 exit 0
+
